layout: stacked
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  # sort_by options:
  #   - stars
  #   - pushed
  limit: 6
  exclude:
    forks: false
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: pedrobarbiero
  medium: pedrobarbiero
  # stackoverflow: your_user_id
  # telegram: your_username
  twitter: pedrobarbiero
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: C#
    web_url: https://docs.microsoft.com/en/dotnet/csharp/
    image_url: https://www.onlinebooksreview.com/uploads/blog_images/2018/01/27_c-sharp-logo-filled.png

  - name: .Net Core
    web_url: https://docs.microsoft.com/en/dotnet/core/
    image_url: https://docs.microsoft.com/pt-br/dotnet/images/hub/netcore.svg

  - name: Elixir
    web_url: https://elixir-lang.org/
    image_url: https://www.sportmonks.com/img/packages/elixir.png

  - name: Phoenix Framework
    web_url: https://phoenixframework.org/
    image_url: https://hexdocs.pm/phoenix/assets/logo.png

  - name: Javascript
    web_url: https://www.javascript.com/
    image_url: https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Unofficial_JavaScript_logo_2.svg/200px-Unofficial_JavaScript_logo_2.svg.png

  - name: Absinthe - Graphql
    web_url: https://hexdocs.pm/absinthe/overview.html
    image_url: https://hexdocs.pm/absinthe/assets/logo.png
    
